/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import COMPONENTES.Mensaje_Dialogo1;
import COMPONENTES.Mensaje_Dialogo2;
import CONTROLADOR_3.c_terreno;
import CONTROLADOR_3.c_usuario;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionListener;
import java.net.URI;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSAnimation;

/**
 *
 * @author lab-1 pc15
 */
public class frm_terreno extends javax.swing.JFrame {

    int x, y;
    private ActionListener la;
    int transicion = 1;

    DefaultTableModel modelo;
    c_terreno ocTerreno = new c_terreno();

    /**
     * Creates new form frm_oficial
     */
    public frm_terreno() {
        initComponents();

        //decoraciones
        //46,78,114
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);

        txt_id.setEnabled(false);
        listar_terrno("");
    }
    
    public static String id_terreno_e="",lote_e="";

    void limpiar() {
        txt_id.setText("");
        txt_lote.setText("");
        txt_manzana.setText("");
    }

    void listar_terrno(String dato) {
        try {
            modelo = ocTerreno.ListarTerreno(dato);
            tabla.setModel(modelo);
        } catch (Exception e) {

            Mensaje_Dialogo2 myDialogo = new Mensaje_Dialogo2(this, true, "error al listar terreno" + e);
        }
    }

    void insertar() {
        try {
            if (txt_lote.getText().isEmpty() || txt_manzana.getText().isEmpty()) {

                Mensaje_Dialogo2 myDialogo = new Mensaje_Dialogo2(this, true, "complete los campos");
            } else {
                ocTerreno.insertarterrno(txt_lote.getText(), txt_manzana.getText());
            }
        } catch (Exception e) {
        }
    }

    void recuperar() {
        int select = tabla.getSelectedRow();
        txt_id.setText(modelo.getValueAt(select, 0).toString());
        txt_lote.setText(modelo.getValueAt(select, 1).toString());
        txt_manzana.setText(modelo.getValueAt(select, 2).toString());

    }

    void modificar() {
        try {
            if (txt_id.getText().isEmpty() || txt_lote.getText().isEmpty() || txt_manzana.getText().isEmpty()) {

                Mensaje_Dialogo2 myDialogo = new Mensaje_Dialogo2(this, true, "complete los campos");
            } else {
                ocTerreno.modificarTerreno(txt_id.getText(), txt_lote.getText(), txt_manzana.getText());
                listar_terrno("");
                
            }

        } catch (Exception e) {

            Mensaje_Dialogo2 myDialogo = new Mensaje_Dialogo2(this, true, "ocurrio un error al modificar ");
        }
    }

    void eliminar() {
        try {

            int sselect = tabla.getSelectedRow();
            if (sselect >= 0) {
                ocTerreno.eliminarTerreno(modelo.getValueAt(sselect, 0).toString());
            } else {

                Mensaje_Dialogo2 myDialogo = new Mensaje_Dialogo2(this, true, "selecione para eliminar");
            }

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panerderecho = new javax.swing.JPanel();
        btn_desplegar = new javax.swing.JLabel();
        btn3 = new LIB.FSButtonMD();
        btn4 = new LIB.FSButtonMD();
        btn5 = new LIB.FSButtonMD();
        btn6 = new LIB.FSButtonMD();
        btn7 = new LIB.FSButtonMD();
        btn9 = new LIB.FSButtonMD();
        btn10 = new LIB.FSButtonMD();
        btn11 = new LIB.FSButtonMD();
        lcliente6 = new javax.swing.JLabel();
        panel_cabecera = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_usuario1 = new rojerusan.RSMaterialButtonRound();
        txt_id = new rojeru_san.RSMTextFull();
        btn_usuario2 = new rojerusan.RSMaterialButtonRound();
        btn_usuario3 = new rojerusan.RSMaterialButtonRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new rojerusan.RSTableMetro();
        txt_manzana = new rojeru_san.RSMTextFull();
        txt_lote = new rojeru_san.RSMTextFull();
        btn_usuario4 = new rojerusan.RSMaterialButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panerderecho.setBackground(new java.awt.Color(46, 78, 114));
        panerderecho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panerderechoMouseDragged(evt);
            }
        });
        panerderecho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panerderechoMousePressed(evt);
            }
        });
        panerderecho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_desplegar.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn_desplegar.setForeground(new java.awt.Color(255, 255, 255));
        btn_desplegar.setText("≡");
        btn_desplegar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_desplegar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_desplegarMouseDragged(evt);
            }
        });
        btn_desplegar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_desplegarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_desplegarMouseEntered(evt);
            }
        });
        panerderecho.add(btn_desplegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 50));

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/terrenos.png"))); // NOI18N
        btn3.setText("TERRENOS");
        btn3.setColorNormal(new java.awt.Color(46, 78, 114));
        btn3.setColorPressed(new java.awt.Color(46, 78, 114));
        btn3.setColorTextHover(new java.awt.Color(46, 78, 114));
        btn3.setColorTextNormal(new java.awt.Color(204, 204, 204));
        btn3.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        panerderecho.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 340, 40));

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/usuarios.png"))); // NOI18N
        btn4.setText("USUARIOS");
        btn4.setColorNormal(new java.awt.Color(46, 78, 114));
        btn4.setColorPressed(new java.awt.Color(46, 78, 114));
        btn4.setColorTextHover(new java.awt.Color(46, 78, 114));
        btn4.setColorTextNormal(new java.awt.Color(204, 204, 204));
        btn4.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        panerderecho.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 340, 40));

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/socios.png"))); // NOI18N
        btn5.setText("SOCIOS");
        btn5.setColorNormal(new java.awt.Color(46, 78, 114));
        btn5.setColorPressed(new java.awt.Color(46, 78, 114));
        btn5.setColorTextHover(new java.awt.Color(46, 78, 114));
        btn5.setColorTextNormal(new java.awt.Color(204, 204, 204));
        btn5.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        panerderecho.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 340, 40));

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/socio_2.png"))); // NOI18N
        btn6.setText("PADRONES");
        btn6.setColorNormal(new java.awt.Color(46, 78, 114));
        btn6.setColorPressed(new java.awt.Color(46, 78, 114));
        btn6.setColorTextHover(new java.awt.Color(46, 78, 114));
        btn6.setColorTextNormal(new java.awt.Color(204, 204, 204));
        btn6.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        panerderecho.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 340, 40));

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/actividades.png"))); // NOI18N
        btn7.setText("ACTIVIDADES");
        btn7.setColorNormal(new java.awt.Color(46, 78, 114));
        btn7.setColorPressed(new java.awt.Color(46, 78, 114));
        btn7.setColorTextHover(new java.awt.Color(46, 78, 114));
        btn7.setColorTextNormal(new java.awt.Color(204, 204, 204));
        btn7.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        panerderecho.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 340, 40));

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/pagos (2).png"))); // NOI18N
        btn9.setText("PAGOS");
        btn9.setColorNormal(new java.awt.Color(46, 78, 114));
        btn9.setColorPressed(new java.awt.Color(46, 78, 114));
        btn9.setColorTextHover(new java.awt.Color(46, 78, 114));
        btn9.setColorTextNormal(new java.awt.Color(204, 204, 204));
        btn9.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        panerderecho.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, 40));

        btn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/sanciones.png"))); // NOI18N
        btn10.setText("SANCIONES");
        btn10.setColorNormal(new java.awt.Color(46, 78, 114));
        btn10.setColorPressed(new java.awt.Color(46, 78, 114));
        btn10.setColorTextHover(new java.awt.Color(46, 78, 114));
        btn10.setColorTextNormal(new java.awt.Color(204, 204, 204));
        btn10.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        panerderecho.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 340, 40));

        btn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/asistencias.png"))); // NOI18N
        btn11.setText("ASISTENCIAS");
        btn11.setColorNormal(new java.awt.Color(46, 78, 114));
        btn11.setColorPressed(new java.awt.Color(46, 78, 114));
        btn11.setColorTextHover(new java.awt.Color(46, 78, 114));
        btn11.setColorTextNormal(new java.awt.Color(204, 204, 204));
        btn11.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        panerderecho.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 340, 40));

        lcliente6.setBackground(new java.awt.Color(255, 255, 255));
        lcliente6.setFont(new java.awt.Font("Poor Richard", 1, 28)); // NOI18N
        lcliente6.setForeground(new java.awt.Color(255, 255, 255));
        lcliente6.setText("APV. LOS ANDENES");
        panerderecho.add(lcliente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, 40));

        getContentPane().add(panerderecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, 0, 340, 600));

        panel_cabecera.setBackground(new java.awt.Color(46, 78, 114));
        panel_cabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_cabeceraMousePressed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 99, 71));
        jLabel16.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel16MouseMoved(evt);
            }
        });
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(255, 99, 71));
        jLabel22.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 204, 204));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Multiply_32px.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel22MouseMoved(evt);
            }
        });
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(46, 78, 114));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE TERRENOS");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel_cabeceraLayout = new javax.swing.GroupLayout(panel_cabecera);
        panel_cabecera.setLayout(panel_cabeceraLayout);
        panel_cabeceraLayout.setHorizontalGroup(
            panel_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cabeceraLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addContainerGap())
        );
        panel_cabeceraLayout.setVerticalGroup(
            panel_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cabeceraLayout.createSequentialGroup()
                .addGroup(panel_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cabeceraLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(panel_cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        btn_usuario1.setBackground(new java.awt.Color(0, 204, 255));
        btn_usuario1.setText("eviar dato ");
        btn_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 170, 50));

        txt_id.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        txt_id.setPlaceholder("id del terreno");
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_idKeyPressed(evt);
            }
        });
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 140, -1));

        btn_usuario2.setBackground(new java.awt.Color(0, 204, 255));
        btn_usuario2.setText("Registar");
        btn_usuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuario2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 190, 50));

        btn_usuario3.setBackground(new java.awt.Color(0, 204, 255));
        btn_usuario3.setText("modificar");
        btn_usuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuario3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 200, 50));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 5 ", "Title 5"
            }
        ));
        tabla.setAltoHead(25);
        tabla.setColorBackgoundHead(new java.awt.Color(102, 176, 202));
        tabla.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tabla.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tabla.setColorFilasBackgound2(new java.awt.Color(156, 204, 221));
        tabla.setColorFilasForeground1(new java.awt.Color(102, 176, 202));
        tabla.setColorFilasForeground2(new java.awt.Color(255, 255, 255));
        tabla.setColorSelBackgound(new java.awt.Color(50, 105, 125));
        tabla.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabla.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setGrosorBordeFilas(0);
        tabla.setMultipleSeleccion(false);
        tabla.setSelectionBackground(new java.awt.Color(255, 0, 0));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 840, 320));

        txt_manzana.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        txt_manzana.setPlaceholder("manzana");
        txt_manzana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_manzanaActionPerformed(evt);
            }
        });
        txt_manzana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_manzanaKeyPressed(evt);
            }
        });
        getContentPane().add(txt_manzana, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 260, -1));

        txt_lote.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        txt_lote.setPlaceholder("lotes");
        txt_lote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loteActionPerformed(evt);
            }
        });
        txt_lote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_loteKeyPressed(evt);
            }
        });
        getContentPane().add(txt_lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 320, -1));

        btn_usuario4.setBackground(new java.awt.Color(0, 204, 255));
        btn_usuario4.setText("Eliminar");
        btn_usuario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuario4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 200, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_desplegarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_desplegarMouseClicked
        // TODO add your handling code here:
        if (transicion == 1) {

            RSAnimation.setMoverDerecha(-205, 0, 10, 8, panerderecho);
            transicion = 0;
        } else if (transicion == 0) {
            RSAnimation.setMoverIzquierda(0, -300, 10, 8, panerderecho);
            transicion = 1;
        }
    }//GEN-LAST:event_btn_desplegarMouseClicked

    private void btn_desplegarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_desplegarMouseEntered
        // TODO add your handling code here:
        //  panerderecho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_desplegarMouseEntered

    private void btn_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuario1ActionPerformed
        // TODO add your handling code here:
       int select = tabla.getSelectedRow();
        if (select >= 0) {
            id_terreno_e = modelo.getValueAt(select, 0).toString();
            lote_e=modelo.getValueAt(select, 1).toString();

            frm_padron frm_ventaa = new frm_padron();
            frm_ventaa.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "seleccione una fila");
        }
    }//GEN-LAST:event_btn_usuario1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
         frm_terreno frm=new frm_terreno();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
         frm_usuarios frm=new frm_usuarios();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        frm_padron frm=new frm_padron();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
         frm_sancion frm=new frm_sancion();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn11ActionPerformed

    private void txt_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyPressed


    }//GEN-LAST:event_txt_idKeyPressed

    private void btn_usuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuario2ActionPerformed
        // TODO add your handling code here:
        insertar();
        listar_terrno("");
        limpiar();
    }//GEN-LAST:event_btn_usuario2ActionPerformed

    private void btn_usuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuario3ActionPerformed
        // TODO add your handling code here:
        modificar();
        listar_terrno("");
        limpiar();
    }//GEN-LAST:event_btn_usuario3ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        //         String coddetallepedido= TablaDetallepedido.getValueAt(TablaDetallepedido.getSelectedRow(), 1).toString();
        //         String vaorrr = String.valueOf(TablaDetallepedido.getValueAt(TablaDetallepedido.getSelectedRow(),0));
        //        String codpedido =TablaDetallepedido.getValueAt(TablaDetallepedido.getSelectedRow(), 2).toString();
        //        String codproducto=TablaDetallepedido.getValueAt(TablaDetallepedido.getSelectedRow(), 3).toString();
        //        String cantidad= TablaDetallepedido.getValueAt(TablaDetallepedido.getSelectedRow(), 4).toString();
        //        String precio=TablaDetallepedido.getValueAt(TablaDetallepedido.getSelectedRow(), 5).toString();
        //        String subtotal=TablaDetallepedido.getValueAt(TablaDetallepedido.getSelectedRow(), 6).toString();
        //        txtcodigo.setText(TablaDetallepedido.getValueAt(1,3)+"");
        //        txtpedido.setText(coddetallepedido);
        //        txtproducto.setText(coddetallepedido);
        //        txtcantidad.setText(coddetallepedido);
        //        txtprecio.setText(coddetallepedido);
        //        txtsubtotal.setText(coddetallepedido);
        //        txtsubtotal.setText("ffff");
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed

        // TODO add your handling code here:
        recuperar();
    }//GEN-LAST:event_tablaMousePressed

    private void txt_manzanaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_manzanaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_manzanaKeyPressed

    private void jLabel22MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseMoved
        // TODO add your handling code here:
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jLabel22MouseMoved

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        this.dispose();
        //  Mensaje_Dialogo1 myDialogo = new Mensaje_Dialogo1(this, true, "Desea cerrar");

    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        // TODO add your handling code here:
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel16MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseMoved
        // TODO add your handling code here:
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jLabel16MouseMoved

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jLabel16MouseExited

    private void txt_manzanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_manzanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_manzanaActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void panerderechoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panerderechoMousePressed
//        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panerderechoMousePressed

    private void btn_desplegarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_desplegarMouseDragged
        // TODO add your handling code here:
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_btn_desplegarMouseDragged

    private void panerderechoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panerderechoMouseDragged
//        // TODO add your handling code here:
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_panerderechoMouseDragged

    private void panel_cabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_cabeceraMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panel_cabeceraMousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_formMouseDragged

    private void txt_loteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loteActionPerformed

    private void txt_loteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_loteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loteKeyPressed

    private void btn_usuario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuario4ActionPerformed
        // TODO add your handling code here:
        eliminar();
        listar_terrno("");
        limpiar();
    }//GEN-LAST:event_btn_usuario4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_terreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_terreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_terreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_terreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_terreno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btn10;
    private LIB.FSButtonMD btn11;
    private LIB.FSButtonMD btn3;
    private LIB.FSButtonMD btn4;
    private LIB.FSButtonMD btn5;
    private LIB.FSButtonMD btn6;
    private LIB.FSButtonMD btn7;
    private LIB.FSButtonMD btn9;
    private javax.swing.JLabel btn_desplegar;
    private rojerusan.RSMaterialButtonRound btn_usuario1;
    private rojerusan.RSMaterialButtonRound btn_usuario2;
    private rojerusan.RSMaterialButtonRound btn_usuario3;
    private rojerusan.RSMaterialButtonRound btn_usuario4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lcliente6;
    private javax.swing.JPanel panel_cabecera;
    private javax.swing.JPanel panerderecho;
    private rojerusan.RSTableMetro tabla;
    private rojeru_san.RSMTextFull txt_id;
    private rojeru_san.RSMTextFull txt_lote;
    private rojeru_san.RSMTextFull txt_manzana;
    // End of variables declaration//GEN-END:variables
}
